version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx-alpine
        ports:
            - 80:80
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./public_html:/public_html
        networks:
            - nginxphp
    php:
        image: php:7.1.11-fpm-alpine
        container_name: php-7.1.11-fpm-alpine
        volumes:
            - ./public_html:/public_html
        expose:
            - 9000
        networks:
            - nginxphp

networks:
    nginxphp: